### ISSUE TITLE
Public scraping methods fail due to login screen on Instagram on production builds

### ISSUE THREAD

**Issue by wjx0820** [oorestisime/gatsby-source-instagram#24]
I use this plugin in my demo and could not work, it says could not fetch instagram posts, no Gatsby nodes generated(I did't use any token and just want to Public scraping for posts). So I cloned your repo, cd into /example, yarn install and run 'npm run develop'. And then it seems like the same problem happened. Wonder to know if i am missing something? Thanks!

**Comment by oorestisime** [comment]
This is odd.
I pushed a new yarn lock file in the example. i forgot to do so. can you pull yarn install and try again?

**Comment by wjx0820** [comment]
Thanks for the quick reply but it still not work...
Wait a long time and said could not fetch instagram posts...
Is it a temporary situation?

**Comment by oorestisime** [comment]
It works for me. I am not sure what is happening locally for you. Are you able to go on instagram? was it working for you and just broke or never worked?

**Comment by wjx0820** [comment]
I can go to instagram in the browser. But still not work.

Error message like these:
Could not fetch instagram posts. Error status Error: write EPROTO 4472038848:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

warning The gatsby-source-instagram plugin has generated no Gatsby nodes. Do you need it?

My location is China, it must be the issue with GFW...I tried use proxy in the terminal, then npm run develop, but still wait for a long time then failed...😭

**Comment by oorestisime** [comment]
:( I am really sorry but i am not sure how i can help here :( You will need to try with a vpn or something.

**Comment by calpa** [comment]
@Jexxie Instagram maybe blocked in China according to the "law", so you may need to find other way.

This should not be an problem of this plugin.

**Comment by oorestisime** [comment]
Closing this! feel free to reopen if you think there's something to be done in the scope of the plugin!

**Comment by tinoguti** [comment]
I am having trouble with this same description when I try to build my Gatsby app on AWS but when I try locally somehow it works. I thought I solved the problem by updating npm packages and I had 2 successful builds but today it is not building. Any help on how to solve this problem?
Here's a copy of my log with the part where everything seems to start failing:

```
2020-05-10T16:23:33.187Z [INFO]: success createSchemaCustomization - 0.073s
2020-05-10T16:23:33.560Z [WARNING]: warning
                                    Could not fetch instagram posts. Error status TypeError: Cannot read property '0' of undefined
2020-05-10T16:23:33.708Z [WARNING]: warning The gatsby-source-instagram plugin has generated no Gatsby nodes. Do you need it?
2020-05-10T16:23:33.708Z [INFO]: success source and transform nodes - 0.521s
2020-05-10T16:23:33.966Z [INFO]: success building schema - 0.257s
2020-05-10T16:23:34.017Z [INFO]: success createPages - 0.049s
2020-05-10T16:23:34.082Z [INFO]: success createPagesStatefully - 0.065s
2020-05-10T16:23:34.082Z [INFO]: success onPreExtractQueries - 0.000s
2020-05-10T16:23:34.111Z [INFO]: success update schema - 0.028s
2020-05-10T16:23:34.446Z [WARNING]: error There was an error in your GraphQL query:
                                    Cannot query field "allInstaNode" on type "Query".
                                    If you don't expect "allInstaNode" to exist on the type "Query" it is most likely a typo.
                                    However, if you expect "allInstaNode" to exist there are a couple of solutions to common problems:
                                    - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
                                    - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
                                    - You want to optionally use your field "allInstaNode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
                                    It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
                                    https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
2020-05-10T16:23:34.449Z [INFO]: failed extract queries from components - 0.337s
2020-05-10T16:23:34.514Z [WARNING]: npm
2020-05-10T16:23:34.515Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2020-05-10T16:23:34.515Z [WARNING]: npm
```

**Comment by tinoguti** [comment]
Now I am intrigued. I've just redeployed my app and it worked. Any idea why this seems to randomly fail? I wouldn't like to have a few failed builds hoping the next one will be the one every time I need to deploy.

**Comment by oorestisime** [comment]
Hey there, kind of hard  to know without reproduction :/

Is it with public scraping or with the graph api?
Where does this run? amplify?

**Comment by tinoguti** [comment]
Hi. Yes it's running on amplify and with public scrapping, with just an username added to the plugin config parameters.

GraphQL query looks like this: 
`
allInstaNode(limit: 8) {

      edges {
          node {
              id
              username
              caption
              localFile {
                childImageSharp {
                  fixed(width: 500, height: 500) {
                    ...GatsbyImageSharpFixed
                  }
                }
              }
          }
      }
    }
`
It works well with gatsby devleop and gatsby build locally. But having "random" build fails on amplify.

**Comment by oorestisime** [comment]
Yeah query isn't the issue. the error you showed above is when it couldn't get the instagram posts. maybe something wrong with instagram during that particular time? does it still happening?

I just triggered another rebuild on netlify for the example app and seems to be working fine

**Comment by LarsBehrenberg** [comment]
I seem to have the same issue. Just a week ago it seemed to have worked fine.
I am deploying my site with Netlify. With the gatsby develop or build command locally I don't run into issues and even with the NetlifyCLI running the local netlify build command everything is alright. But as soon as I push to Netlify the build fails. 

```
7:18:17 PM: $ yarn build
7:18:17 PM: yarn run v1.22.4
7:18:17 PM: $ gatsby clean && gatsby build
7:18:18 PM: 
7:18:18 PM: info Deleting .cache, public
7:18:18 PM: info Successfully deleted directories
7:18:20 PM: 
7:18:20 PM: success open and validate gatsby-configs - 0.067s
7:18:22 PM: 
7:18:22 PM: success load plugins - 1.694s
7:18:22 PM: 
7:18:22 PM: success onPreInit - 0.016s
7:18:22 PM: success delete html and css files from previous builds - 0.018s
7:18:22 PM: 
7:18:22 PM: success initialize cache - 0.012s
7:18:22 PM: 
7:18:22 PM: success copy gatsby files - 0.047s
7:18:22 PM: 
7:18:22 PM: success onPreBootstrap - 0.010s
7:18:22 PM: 
7:18:22 PM: success createSchemaCustomization - 0.012s
7:18:23 PM: 
7:18:23 PM: warning
7:18:23 PM: Could not fetch instagram posts. Error status TypeError: Cannot read property '0' of undefined
7:18:23 PM: success source and transform nodes - 1.476s
7:18:24 PM: 
7:18:24 PM: success building schema - 0.578s
7:18:24 PM: 
7:18:24 PM: success createPages - 0.240s
7:18:24 PM: success createPagesStatefully - 0.162s
7:18:24 PM: 
7:18:24 PM: success onPreExtractQueries - 0.001s
7:18:24 PM: success update schema - 0.084s
7:18:25 PM: error There was an error in your GraphQL query:
7:18:25 PM: Cannot query field "allInstaNode" on type "Query".
7:18:25 PM: If you don't expect "allInstaNode" to exist on the type "Query" it is most likely a typo.
7:18:25 PM: However, if you expect "allInstaNode" to exist there are a couple of solutions to common problems:
7:18:25 PM: - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
7:18:25 PM: - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
7:18:25 PM: - You want to optionally use your field "allInstaNode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
7:18:25 PM: It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
7:18:25 PM: https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
7:18:25 PM: not finished Generating image thumbnails - 1.265s
7:18:25 PM: failed extract queries from components - 0.823s
```

**Comment by oorestisime** [comment]
I am seeing this now on netlify as well. locally works fine. I am investigating right now

**Comment by oorestisime** [comment]
Well now it went through on netlify. I think maybe network issue? I can't find any way to reproduce locally so not sure what i can do here :/

**Comment by LarsBehrenberg** [comment]
I am really not sure what is happening here, but it seems like this is not the plugins fault? I deployed the same built a couple times on Netlify every time clearing cache before building. The first two times everything works fine and then the 3rd time it breaks. 

````
warning
11:15:23 AM: Could not fetch instagram user. Error status TypeError: Cannot read property '0' of undefined
11:15:23 AM: 
11:15:23 AM: error "gatsby-source-instagram" threw an error while running the sourceNodes lifecycle:
11:15:23 AM: Cannot read property 'id' of null
11:15:23 AM:   74 |   return {
11:15:23 AM:   75 |     type: params.type,
11:15:23 AM: > 76 |     id: datum.id,
11:15:23 AM:      |               ^
11:15:23 AM:   77 |     full_name: datum.full_name,
11:15:23 AM:   78 |     biography: datum.biography,
11:15:23 AM:   79 |     edge_followed_by: datum.edge_followed_by,
11:15:23 AM: 
11:15:23 AM: 
11:15:23 AM: 
11:15:23 AM:   TypeError: Cannot read property 'id' of null
11:15:23 AM:   
11:15:23 AM:   - gatsby-node.js:76 createUserNode
11:15:23 AM:     [repo]/[gatsby-source-instagram]/gatsby-node.js:76:15
11:15:23 AM:   
11:15:23 AM:   - gatsby-node.js:91 processDatum
11:15:23 AM:     [repo]/[gatsby-source-instagram]/gatsby-node.js:91:49
11:15:23 AM:   
11:15:23 AM:   - gatsby-node.js:125 
11:15:23 AM:     [repo]/[gatsby-source-instagram]/gatsby-node.js:125:16
11:15:23 AM:   
11:15:23 AM:   - Array.map
11:15:23 AM:   
11:15:23 AM:   - gatsby-node.js:123 Object.exports.sourceNodes
11:15:23 AM:     [repo]/[gatsby-source-instagram]/gatsby-node.js:123:29
11:15:23 AM:   
11:15:23 AM:   - task_queues.js:97 processTicksAndRejections
11:15:23 AM:     internal/process/task_queues.js:97:5
11:15:23 AM:   
11:15:23 AM: 
11:15:23 AM: not finished source and transform nodes - 1.120s
````
Btw, I am not using an Instagram API, maybe this makes a difference?

**Comment by pul87** [comment]
I'm having the same problem on Netlify, seems an issue related to the platform, on development it works.

**Comment by LarsBehrenberg** [comment]
Anything we can do about it? Some workaround?

**Comment by oorestisime** [comment]
Well the issue is not with the plugin afaict. it is happening when scraping the page doesn't work. But i can't find out whether this is an issue on Netlify (much more likely since it never happens in dev) itself or if Instagram is testing things out. After all the public scraping is extemely dependent on their raw html code :)

Only thing i can susggest if use the API. it worked the whole time i was testing.

Has anybody tried to contact Netlify support to see if anything is off in the network?

**Comment by oorestisime** [comment]
I am re-opening this for visibility among folks checking the issues.

**Comment by dmcreis** [comment]
Same problem happening here. I tried a couple of times today and the build is failing. is there any workaround for this? @oorestisime thanks for all your replies :)

**Comment by tonilaukka** [comment]
I'm having the same issue although my builds fail randomly and hitting redeploy helps.

This is the error message:
```
11:55:31 PM: error There was an error in your GraphQL query:
11:55:31 PM: - Unknown field 'allInstaNode' on type 'Query'.
11:55:31 PM: failed extract queries from components - 0.464s
```

**Comment by LarsBehrenberg** [comment]
@oorestisime thanks for reopening this issue! 

I have posted this on the Netlify community as well. 
[https://community.netlify.com/t/deploying-a-gatsby-site-on-netlify-using-the-gatsby-source-instagram-plugin-failing-on-build-time-issue-with-netlify-fetching-data-from-instagram-cannot-reproduce-locally/15957](https://community.netlify.com/t/deploying-a-gatsby-site-on-netlify-using-the-gatsby-source-instagram-plugin-failing-on-build-time-issue-with-netlify-fetching-data-from-instagram-cannot-reproduce-locally/15957)

**Comment by xanderjl** [comment]
I've also been running into this issue. Noticed a string of failed builds on the deploy dashboard with the same error. I hope your Netlify post brings attention to the problem!

**Comment by LarsBehrenberg** [comment]
If you could join the netlify post and let people know you have had the same issue, maybe it will gain more attention. Would really appreciate it! Thanks so much here already for all the help!

**Comment by ashishterp** [comment]
I'm having the same issue on Netlify as of last week. I forked a copy of the plugin and added some logging and it looks like Instagram is returning a login page for some reason:

```
2:11:52 AM: { LoginAndSignupPage:
2:11:52 AM:    [ { captcha: [Object],
2:11:52 AM:        gdpr_required: false,
2:11:52 AM:        tos_version: 'row',
2:11:52 AM:        username_hint: '' } ] }
```

I tried faking the User Agent on the axios request and that didn't work either. What's weird is that it works fine locally, so maybe it is something on the IG side about where the request is coming from that is triggering it generating a login page.

**Comment by oorestisime** [comment]
So from #152 i am reposting the same link here https://stackoverflow.com/questions/57624387/dont-have-profilepage-index-but-i-have-loginandsignuppage
`The issue is Instagram over the last week or so has restricted their unlogged-in (guest) access (based on IP address).`

This is why we have a login now.

**Comment by oorestisime** [comment]
I am sorry this is failing for you folks, i ll try over the next days to work something out using this https://github.com/oorestisime/gatsby-source-instagram/issues/131#issuecomment-603282394
hopefully that won't get a login screen. I don't have much time though in the next 2 days so if anyone wants to come up with a PR, more than welcome :)

**Comment by tinoguti** [comment]
I would just like to add that I am also having this issue on my Amazon Amplify app. I went through 8 failed builds to get one right.

**Comment by oorestisime** [comment]
Sorry for the trouble this is causing, I made time for working on this tonight. give me a few hours please :)

**Comment by johnkavanagh** [comment]
@oorestisime 

> Sorry for the trouble this is causing, I made time for working on this tonight. give me a few hours please :)

Just in case nobody else says it: thank you!  I know you're not in any way obligated to fix everybody else's broken builds.  Your plugin is awesome (when it's working), thank you for looking at it again for us now.

**Comment by LarsBehrenberg** [comment]
@oorestisime 
Yes, have to agree with @johnkavanagh! Thanks so much for the plugin in the first place and all the effort to keep it updated!

**Comment by oorestisime** [comment]
Hey folks thanks for the kind words. I released 0.7.1 with the new endpoint modification but it seems problem persist. If any of you could test as well to confirm this 🙏 

Not sure what next steps are if this persists :(

**Comment by xanderjl** [comment]
Can confirm the issue is still persisting on 7.1

```
10:41:42 AM: error There was an error in your GraphQL query:
10:41:42 AM: Cannot query field "allInstaNode" on type "Query".
10:41:42 AM: If you don't expect "allInstaNode" to exist on the type "Query" it is most likely a typo.
10:41:42 AM: However, if you expect "allInstaNode" to exist there are a couple of solutions to common problems:
10:41:42 AM: - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
10:41:42 AM: - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
10:41:42 AM: - You want to optionally use your field "allInstaNode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
10:41:42 AM: It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
10:41:42 AM: https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
10:41:42 AM: failed extract queries from components - 1.171s
```

Thank you for your quick response! Appreciate all of the work you've put into this :)

**Comment by oorestisime** [comment]
I am trying to think of next steps here: 

* if anyone manages to reproduce locally i would love the html of the page to see what's included in that new screen. Or if you are using the new url with `?__a=1` in it then just that.

* for anyone not midning to create an access token and go through https://github.com/oorestisime/gatsby-source-instagram#instagram-graph-api-token then this is an alternative.

**Comment by marcusps11** [comment]
Same problem here can not produce locally only when i try and build - at least i know i am not going mad.

**Comment by cbaucom** [comment]
I can also confirm this is an issue for me when trying to build on Netlify. Failed when I was at version 0.5.0 and also after updating to 0.7.1. 

```
12:33:39 AM: Could not fetch instagram posts. Error status TypeError: Cannot read property 'user' of undefined
12:33:43 AM: warning The gatsby-source-instagram plugin has generated no Gatsby nodes. Do you need it?
12:33:43 AM: success source and transform nodes — 4.429 s
12:33:43 AM: success building schema — 0.400 s
12:33:43 AM: success createPages — 0.027 s
12:33:43 AM: success createPagesStatefully — 0.043 s
12:33:43 AM: success onPreExtractQueries — 0.002 s
12:33:43 AM: success update schema — 0.024 s
12:33:44 AM: error GraphQL Error Encountered 1 error(s):
12:33:44 AM: - Unknown field 'allInstaNode' on type 'Query'.
12:33:44 AM:       file: /opt/build/repo/src/components/Instagram.js
```

Does not fail for me locally on either `develop` or `build`

**Comment by wjchat** [comment]
Does your plugin use Instagram's newer Graph API or the legacy API? BTW, it is a really great plugin. I'm having similar issues with my app deployed on AWS amplify. Reading about how the legacy api is being disabled by Instagram. maybe this has something to do with it?

**Comment by oorestisime** [comment]
The api uses the newer Graph api and afaiu it is not affected.

**Comment by oorestisime** [comment]
I logged the output, and its a plain login wall. I can't find anything usefull there. Not sure what i can do next folks. seems like i need to remove public scraping methods. 

I d love your input here.

**Comment by DevanB** [comment]
I've been trying to follow along with the instructions to setup an access token, but they seem outdated and/or not thorough enough to follow. If you do remove public scraping, perhaps someone can give a good walk through of setting up and getting an access token with screenshots and/or videos.

**Comment by oorestisime** [comment]
I am happy to accept any PRs on that end. It's been a year i did those steps myself and i remember it was quite tedious.

**Comment by luchoster** [comment]
I've been thinking about making a port from this plugin, to a React component that we can just pull data on page load. Finally last night I decided to start it, and today I encounter this problem with one of the sites I maintain.

Anyway, long story short I published: [react-ig](https://www.npmjs.com/package/@luchoster/react-ig) - It displays a grid of the posts, at the moment I only had the hashtag working, but I just added the username prop:

`<InstagramPosts username="vegas" />`

And you'll get the latest 12 posts, this will hit the ig user url, on every page load, so you'll get fresh posts every time. Or use the hashtag, as it says on the readme.

I'm only posting it here, in case anyone needs a quick fix on their build and this could help.

**Comment by ColinTS** [comment]
@luchoster Thanks for this, is the UI configurable?

**Comment by luchoster** [comment]
> @luchoster Thanks for this, is the UI configurable?

Not really, but if you want to create an issue https://github.com/luchoster/react-ig/issues I'll see what I can do.

**Comment by diogocapela** [comment]
I'm having the same problem. The development and build instances both work locally but they fail when deployed on to Netlify. Here is the Netlify deploy error log:

```
1:13:09 AM: error There was an error in your GraphQL query:
1:13:09 AM: Cannot query field "allInstaNode" on type "Query".
1:13:09 AM: If you don't expect "allInstaNode" to exist on the type "Query" it is most likely a typo.
1:13:09 AM: However, if you expect "allInstaNode" to exist there are a couple of solutions to common problems:
1:13:09 AM: - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
1:13:09 AM: - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
1:13:09 AM: - You want to optionally use your field "allInstaNode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
1:13:09 AM: It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
1:13:09 AM: https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
1:13:09 AM: failed extract queries from components - 0.220s
1:13:09 AM: npm
1:13:09 AM:  ERR! code ELIFECYCLE
1:13:09 AM: npm ERR!
1:13:09 AM:  errno 1
1:13:09 AM: npm ERR! jam-stack-boiler@0.0.1 build: `gatsby build`
1:13:09 AM: npm ERR! Exit status 1
1:13:09 AM: npm ERR!
1:13:09 AM: npm ERR! Failed at the jam-stack-boiler@0.0.1 build script.
1:13:09 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1:13:09 AM: npm
1:13:09 AM:  ERR! A complete log of this run can be found in:
1:13:09 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-06-05T00_13_09_340Z-debug.log
```

**Comment by zamson** [comment]
Same problem here. So is it only public fetching that is not working?

Public scraping fails locally and on Netlify build

Using `gatsby-source-instagram@0.7.2`

**Comment by oorestisime** [comment]
Yes public scraping fails due to their login screen but the graph api works. 

if you are having issues generating a token then this might help you https://github.com/oorestisime/gatsby-source-instagram/issues/156 cc @DevanB 

I ll wait a few more days in case something else on that doc section needs modification before i go and update it.

**Comment by tinoguti** [comment]
Could someone sum up the current status up to this point?
I will need to do a build of my app sometime soon but it seems like the build won't work. 
What's the alternative? 
Thank you

**Comment by sjelfull** [comment]
@tinoguti The only alternative is doing authorized calls to the Graph API.

I'm in the middle of generating a access token, and its confusing as hell, especially as the instructions doesn't match what i'm seeing.

**Comment by oorestisime** [comment]
I know of one inconsistency on the docs already which is the permissions because last month they changed. https://developers.facebook.com/docs/facebook-login/permissions/#reference-manage_pages

what else is missing? if you folks don't let me know i can't actually update them :/

**Comment by oorestisime** [comment]
@sjelfull Please let me know anything confusing or inconsistent i ll try to help you generate the token and update the docs accordingly :) 
Same for anybody else!

**Comment by sjelfull** [comment]
Let me see if I can boil it down - right now i'm so far down the hole that i'm not sure where I went wrong.

I'll add notes inline in the steps:

1. You need to have a Facebook page (I know... :/)
1. Go to your site settings -> Instagram -> Login into your Instagram account 
1. Create a [app](https://developers.facebook.com/apps/) **As far as I can tell, after this step, we need to add Instagram below the heading Add a Product on the FB apps dashboard.**
1. Go to the [Graph API Explorer](https://developers.facebook.com/tools/explorer/)
   1. Select your App from the top right dropdown menu **Its unclear what you mean by the top right dropdown menu here. If you select the app under My apps, which is the only relevant link I can see in the top right corner, you get brough out of the Graph explorer and to the dashboard**
   1. Select "Get User Access Token" from dropdown (right of access token field) and select needed permissions (manage_pages, pages_show_list, instagram_basic) **Sounds like the UI has changed a bit here. The previous step, where you select the app, is now below the Get Access Token button, in the field labeled Facebook App**
   1. Click "Generate Access Token" **Which permissions do we need to ask for for this to be able to access the right Instagram account? What fields/path do we use in the explorer?**
   1. Copy user access token
1. [Access Token Debugger](https://developers.facebook.com/tools/debug/accesstoken/):
   1. Paste copied token and press "Debug"
   1. Press "Extend Access Token" and copy the generated long-lived user access token
1. [Graph API Explorer](https://developers.facebook.com/tools/explorer/):
   1. Paste copied token into the "Access Token" field
   1. Make a GET request with "PAGE_ID?fields=access_token"
   1. Find the permanent page access token in the response (node "access_token")
1. [Access Token Debugger](https://developers.facebook.com/tools/debug/accesstoken/):
   1. Paste the permanent token and press "Debug"
   1. "Expires" should be "Never"
   1. Copy the **access token**
1. [Graph API Explorer](https://developers.facebook.com/tools/explorer/):
   1. Make a GET request with "PAGE_ID?fields=instagram_business_account" to get your **Business ID** **The business ID does not show up here. I only get the id of the page and nothing else.**

**Comment by oorestisime** [comment]
For the permissions you will need to add the  pages_manage_ads, pages_manage_metadata, pages_read_engagement, and pages_read_user_content,pages_show_list, instagram_basic (basically the ones listed in step 2 without manage_pages but with the ones it got replaced with). Hope this gets you unblocked.

I ll try tomorrow to go through all the steps and leave an update here. Thanks this was very helpful!

**Comment by hvitis** [comment]
I´m having the same issue on updated plugin, on local works fine.

Can I help in any way?

**Comment by oorestisime** [comment]
Unfortunately the public scraping method doesn't work on build in infrastructure. not sure when they decide to add the login screen either IP based or some kind of rate limit.
In any case i think we can't bypass it (but open to suggestions).

You can test generating the access token in case you find more inconsistencies or you might want to open a PR to update them :)

**Comment by LarsBehrenberg** [comment]
I started using [this approach](https://codesandbox.io/s/pw363kq3nm) for public scraping instead. I wonder wether the way images are being fetched with that approach could also be implemented in gatsby-source-instagram?

**Comment by tinoguti** [comment]
> I started using [this approach](https://codesandbox.io/s/pw363kq3nm) for public scraping instead. I wonder wether the way images are being fetched with that approach could also be implemented in gatsby-source-instagram?

This approach is working for me so far. Thanks. Although I wonder for how long it will work because it seems like it depends on a query id that might change in the future.

**Comment by oorestisime** [comment]
Yeah not sure i udnerstand what query id is. also, have you tried this request from a build such as netlify?

**Comment by will-t-harris** [comment]
I'm also not sure what that query id is, but I just built that solution with netlify and it works.

I also refactored it into a hook, which I'm considering throwing on npm. At least I was before I realized it was using that `query_id`. I'd be shocked if that didn't change in the future.

https://gist.github.com/will-t-harris/4b8671315fb77d541b6ad34276acfdb6

**Comment by will-t-harris** [comment]
It seems that `query_id` has been the same since 2017...perhaps this approach is more reliable than it looks at first glance.

https://stackoverflow.com/a/47243409/4552841

**Comment by tinoguti** [comment]
I was able to do a build on Amplify with that query id approach. It's working fine for now. I did try the whole Facebook develop access token process with no luck. It's quite tedious and requires time to set up.

**Comment by oorestisime** [comment]
OK great thanks folks, i ll add this in 0.7.3 to test. unless somebody wants to PR this :D

**Comment by oorestisime** [comment]
I am trying this now. i ll keep you posted

**Comment by oorestisime** [comment]
I just published  `0.8.0-beta.0` with the change. My netlify build passed  that stepped but failed because hashtag scraping still doesn't work. I would like some more feedback from you people though.

In that version public scraping of hashtags and profile information is not working. If any of you knows of a way to public scraping hashtags then i am all eyes to get it to work.


Public scraping for public posts is supposed to work though.

In order to use this you need to pass an instagram id instead of a username. I used https://codeofaninja.com/tools/find-instagram-user-id to get an id. (You pass it in the username config, i want to make sure this work before i jump on API changes).

Another change is on the instagram node the username is also going to be the instagram id you provided. Unfortunately instagram doesn't pass in the username when querying like that. 

I managed to 50 posts instead of 12 so this is good news.

**Comment by will-t-harris** [comment]
Thanks for trying that out so quickly @oorestisime.

That version seems to work for me, locally and on my build in netlify.

**Comment by dmcreis** [comment]
thanks a lot for this @oorestisime . i will have a go at the new update. when i do `npm outdated` the only last version that appears available is 0.7.2. any idea why?

**Comment by oorestisime** [comment]
I think because i published a beta one. can you manually replace the version in package.json and then npm install?

**Comment by abepuentes** [comment]
Thanks @oorestisime, I've been testing 0.8.0-beta.0 and its works on develop en on netlify. One comment though, searching for this issue I found the following on instagram API docs. The ID you get from https://codeofaninja.com/tools/find-instagram-user-id es whats facebooks its calling "Legacy ID" and will be deprecated on September 30th, 2020. On the new graph.instagram.com API this field is call ig_id more infor here  https://developers.facebook.com/docs/instagram-basic-display-api/. I try the new user "ID" field and doenst work with the "query_id" method.

**Comment by oorestisime** [comment]
Yes indeed its two different ids and i couldn't get it to work with the new id either. Probably that means that this method will work only until then :/ unless there's a way to specify ig_id in the query. i ll test this out tomorrow and get back here.

Still maybe a nice trade-off for a few months giving us time to find new solutions :)

**Comment by oorestisime** [comment]
I went through the steps again. here's what i found and let me know if this works for you and if it is clearer:


1. You need to have a Facebook page (I know... :/)
1. Go to your site settings -> Instagram -> Login into your Instagram account
1. Create a [app](https://developers.facebook.com/apps/)
1. Go to the [Graph API Explorer](https://developers.facebook.com/tools/explorer/)
   1. Make sure you are using v7 as api version
   1. Select your facebook app
   1. Click "Generate Access Token"
   1. Add the following permissions (pages_manage_ads, pages_manage_metadata, pages_read_engagement, pages_read_user_content, pages_show_list, instagram_basic)
   1. Make a GET request at `me/accounts`
   1. copy the access_token in the response (we call this **temporary_token**)
   1. click on the id to change the explorer url and append `?fields=instagram_business_account&access_token={access-token}`
   1. save your `instagram_business_account.id`, this is your **instagram_id**
1. [Access Token Debugger](https://developers.facebook.com/tools/debug/accesstoken/):
   1. Paste your temporary_token and press "Debug"
   1. You should see this token now expires in 3 months
   1. Press "Extend Access Token" and press the new debug that appears next to the token
   1. You should see this token now never expires
   1. Copy this new token (we will call this **access_token**)

With these two information you can now use the plugin as:

```
{
  resolve: `gatsby-source-instagram`,
  options: {
    username: username,
    access_token: access_token,
    instagram_id: instagram_id,
  },
},
```

**Comment by homearanya** [comment]
HI @oorestisime,

Thanks for your efforts. I follow your steps above and it worked great for 2 of 3 Instagram accounts I manage. However, on the 3rd one I get the following error:

```
Could not download file, error is failed to process https://scontent.cdninstagram.com/v/t51.2885-15/20394100_1101681946599058_7213100928830799872_n.jpg?_nc_cat=106&_nc_sid=8ae9d6&_nc_eui2=AeHWKYmdMLbZjaOXZuGs-eS4D0Tz10hy7CAPRPPXSHLsIDftwoCaG0zGDF4xQrR4-Yw&_nc_ohc=f4ppFsxMW14AX94zd7i&_nc_ht=scontent.cdninstagram.com&oh=bdf4d988d590b0ce1268b3ff9c5d8c09&oe=5F0272A5

TimeoutError: Timeout awaiting 'request' for 30000ms

```
for every single post of that account and none of the posts are accessible by graphql.

Any idea why this is happening?

Thanks in advance

**Comment by oorestisime** [comment]
Sorry no idea :(

**Comment by dbertella** [comment]
Too much pain to go through fb registration and ig apis, Beta version worked for me. Hopefully we will find a solution to make it permanent. Also likes are not supported with the new scraping apparently, my build was failing because I included them in my query.

**Comment by jpmarra** [comment]
0.8.0-beta.0 has worked for me both locally and through Netlify. I'm going through the steps to authenticate now for a more long term fix.

**Comment by zamson** [comment]
> I went through the steps again. here's what i found and let me know if this works for you and if it is clearer:
> 
> 1. You need to have a Facebook page (I know... :/)
> 2. Go to your site settings -> Instagram -> Login into your Instagram account
> 3. Create a [app](https://developers.facebook.com/apps/)
> 4. Go to the [Graph API Explorer](https://developers.facebook.com/tools/explorer/)
>    
>    1. Make sure you are using v7 as api version
>    2. Select your facebook app
>    3. Click "Generate Access Token"
>    4. Add the following permissions (pages_manage_ads, pages_manage_metadata, pages_read_engagement, pages_read_user_content, pages_show_list, instagram_basic)
>    5. Make a GET request at `me/accounts`
>    6. copy the access_token in the response (we call this **temporary_token**)
>    7. click on the id to change the explorer url and append `?fields=instagram_business_account&access_token={access-token}`
>    8. save your `instagram_business_account.id`, this is your **instagram_id**
> 5. [Access Token Debugger](https://developers.facebook.com/tools/debug/accesstoken/):
>    
>    1. Paste your temporary_token and press "Debug"
>    2. You should see this token now expires in 3 months
>    3. Press "Extend Access Token" and press the new debug that appears next to the token
>    4. You should see this token now never expires
>    5. Copy this new token (we will call this **access_token**)
> 
> With these two information you can now use the plugin as:
> 
> ```
> {
>   resolve: `gatsby-source-instagram`,
>   options: {
>     username: username,
>     access_token: access_token,
>     instagram_id: instagram_id,
>   },
> },
> ```

Regarding step 1. Do you mean a business account or my personal page? I'm trying to setup an fb app for a client but the instagram capabilities does not show up. The Instagram account is linked to their business account. Puh.. wish public scraping was working.

**Comment by zamson** [comment]
> 0.8.0-beta.0 has worked for me both locally and through Netlify. I'm going through the steps to authenticate now for a more long term fix.

Worked how, with public scraping?

**Comment by MilosJo** [comment]
> > I went through the steps again. here's what i found and let me know if this works for you and if it is clearer:
> > 
> > 1. You need to have a Facebook page (I know... :/)
> > 2. Go to your site settings -> Instagram -> Login into your Instagram account
> > 3. Create a [app](https://developers.facebook.com/apps/)
> > 4. Go to the [Graph API Explorer](https://developers.facebook.com/tools/explorer/)
> >    
> >    1. Make sure you are using v7 as api version
> >    2. Select your facebook app
> >    3. Click "Generate Access Token"
> >    4. Add the following permissions (pages_manage_ads, pages_manage_metadata, pages_read_engagement, pages_read_user_content, pages_show_list, instagram_basic)
> >    5. Make a GET request at `me/accounts`
> >    6. copy the access_token in the response (we call this **temporary_token**)
> >    7. click on the id to change the explorer url and append `?fields=instagram_business_account&access_token={access-token}`
> >    8. save your `instagram_business_account.id`, this is your **instagram_id**
> > 5. [Access Token Debugger](https://developers.facebook.com/tools/debug/accesstoken/):
> >    
> >    1. Paste your temporary_token and press "Debug"
> >    2. You should see this token now expires in 3 months
> >    3. Press "Extend Access Token" and press the new debug that appears next to the token
> >    4. You should see this token now never expires
> >    5. Copy this new token (we will call this **access_token**)
> > 
> > With these two information you can now use the plugin as:
> > ```
> > {
> >   resolve: `gatsby-source-instagram`,
> >   options: {
> >     username: username,
> >     access_token: access_token,
> >     instagram_id: instagram_id,
> >   },
> > },
> > ```
> 
> Regarding step 1. Do you mean a business account or my personal page? I'm trying to setup an fb app for a client but the instagram capabilities does not show up. The Instagram account is linked to their business account. Puh.. wish public scraping was working.

Following this steps my gatsby site is finally working and fetching instagram posts.
Only thing I didn't manage to change  is to extend 3months token expiration.
Can confirm that these steps are legit.

Thanks @oorestisime

**Comment by oorestisime** [comment]
Ok folks, i ll wait another couple of days for some more feedback and then release 1.0 with the list of breaking changes and updated doc section! thank you all for your patience :)

**Comment by jpmarra** [comment]
> > 0.8.0-beta.0 has worked for me both locally and through Netlify. I'm going through the steps to authenticate now for a more long term fix.
> 
> Worked how, with public scraping?

Sorry for the incomplete response. the beta release allowed for public scraping both locally and through Netlify.

I ended up creating an auth token by following the steps listed by @oorestisime, however I could only extend the access token three months, as stated by @MilosJo.

**Comment by NeversSync** [comment]
Having the same issue. Just attempted to go through the GraphApi setup (tedious and still not confident I did it correcty) and am getting this error both on development and deployment to Netlify. 

Netlify build error:
<img width="1278" alt="Screen Shot 2020-06-08 at 6 37 38 PM" src="https://user-images.githubusercontent.com/20482636/84096751-8b560080-a9b7-11ea-99d8-8efac86288d6.png">

Here is my package, config and query:
`<StaticQuery
    query={graphql`
      query myQuery {
        allInstaNode {
          edges {
            node {
              localFile {
                childImageSharp {
                  fluid(maxHeight: 500, maxWidth: 500, quality: 90) {
                    ...GatsbyImageSharpFluid_withWebp
                  }
                }
              }
            }
          }
        }
      }
    `}`

![Screen Shot 2020-06-08 at 6 39 24 PM](https://user-images.githubusercontent.com/20482636/84096680-619cd980-a9b7-11ea-8b11-0d5e90e42040.png)

Config:
`{
      resolve: `gatsby-source-instagram`,
      options: {
        username: `steadyhandtea`,
        access_token: '{access token}',
        instagram_id: '{business id},
      }
    },`


Thanks for all the work on this! Hope it can all be resolved.

**Comment by hzburki** [comment]
The solution provided in this [comment](https://github.com/oorestisime/gatsby-source-instagram/issues/24#issuecomment-640086393) worked for public posts. Netlify build succeeded but I had to remove `likes` from the query.

**Comment by oorestisime** [comment]
https://github.com/oorestisime/gatsby-source-instagram/pull/158 fixed the likes issue. i ll release in 2 days

**Comment by yone920** [comment]
Any good news on this problem?

**Comment by mattortiz** [comment]
Hi @oorestisime , 

I used the instructions provided above. As with prior comments, the instructions are difficult to follow and I'm not sure if I'm doing it correctly as a result. I did in the end get the instagram-id, temp-access-token and extended access-token (but only good through august 12, for some reason). 

Still getting the following error (locally):  
11:9  error  Cannot query field "allInstaNode" on type "Query"  graphql/template-strings

My gatsby.config settings with input from @NeversSync above: 
      resolve: `gatsby-source-instagram`,
      options: {
        username: "envyforge",
        access_token: access-token, // extended access token from instructions
        instagram_id: instagram-id, // instagram id from instructions 
      },

package.json setting: 
    "gatsby-source-instagram": "0.8.0-beta.0",

Just providing input. I look forward to the fix and instructions. 

Take care, 

Matt

**Comment by oorestisime** [comment]
Can anyone try getting a permanent token using this https://github.com/Bnjis/Facebook-permanent-token-generator ? if this works then probably i could do this inside the plugin directly and spare people some manual steps.

other areas of research someone can help me with is whether there's a way to automate getting even a short lived token. The plugin doesn't really need a permanent token if we manage to automate the process of getting a short lived one because it will get a new token on each build.

In the meantime i ll handle release of 0.8. 

once again sorry for  the trouble this is causing

**Comment by oorestisime** [comment]
I just released 0.8
https://github.com/oorestisime/gatsby-source-instagram/releases/tag/v0.8.0

Make sure to change your instagram id.

**Comment by Mike-Huggins** [comment]
Sorry not sure I understand the thread here and the docs might not have been updated. My graphql looks like: 
```query {
      allInstaNode(limit: 5) {
        nodes {
          id
          caption
          username
          localFile {
            childImageSharp {
              fluid(maxWidth: 200, maxHeight: 200, quality: 100) {
                ...GatsbyImageSharpFluid_withWebp
              }
            }
          }
        }
      }
    }

and my gatsby config:  {
      resolve: 'gatsby-source-instagram',
      options: {
        username: 'username',
      },
    },```

what do I need to do to get this working on netlify deploy please?

**Comment by oorestisime** [comment]
i think this explains it good https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-posts `need to pass the concerning username id. You can find it https://codeofaninja.com/tools/find-instagram-user-id`
if this is not clear feel free to PR something that would have helped you :)

**Comment by Mike-Huggins** [comment]
My apologies, this was entirely my own fault. Thanks for your effort to fix. I thought I had updated to 0.8 but I had not, for anyone following the thread then this is what my code now looks like with version 0.8 and adding in the user id as above: 

```const useInstagram = () => {
  const data = useStaticQuery(graphql`
    query {
      allInstaNode(limit: 5, sort: { fields: [timestamp], order: DESC }) {
        edges {
          node {
            id
            caption
            localFile {
              childImageSharp {
                fluid(maxWidth: 200, maxHeight: 200, quality: 100) {
                  ...GatsbyImageSharpFluid_withWebp
                }
              }
            }
          }
        }
      }
    }
  `);

  return data.allInstaNode.edges.map(node => ({
    ...node.node.localFile.childImageSharp,
    id: node.node.id,
    caption: node.node.caption,
    username: node.node.username,
  }));
};```

**Comment by mattortiz** [comment]
@oorestisime , the 0.8.0 release and updated documentation got me freed up. Thank you very much! 

Matt

**Comment by andregmoeller** [comment]
First off, thank you for all the work you put into developing and maintining this plugin! Probably it is too late now, but I feel that the configuration parameter / option 'username' should have been renamed to 'instagram_id' – the semantic meaning of the option username has changed. It is not any longer the username.

**Comment by oorestisime** [comment]
Yeah it crossed my mind right after i hit release :/ 
i ll do this in 1.0 which is as soon as i figure out how to properly get a token for the graph api!

**Comment by maxsteenbergen** [comment]
I'm happy to have found this thread! In my case, we only used the hashtag scraping which isn't fixed in 0.8.0 yet. Can we expect that to return some day or has instagram permanently broken that?

**Comment by oorestisime** [comment]
i haven't found any way to do it yet. i also haven't looked if the Graph Api can return this information.

Happy to receive help on that end :)

**Comment by maxsteenbergen** [comment]
I'd love to help out, even though my experience is limited. Any ideas as to why cloud builders fail whereas local builds work? (Note: it's not just Netlify, GitLab usually fails too but sporadically succeeds)

**Comment by oorestisime** [comment]
Instagram is adding a login screen . i suppose it is adding for when something is requesting it a lot without login but we can't know.

**Comment by ngerbauld** [comment]
Hi @oorestisime !

I am not sure what I am missing!

After updating the gatsby-source-instagram to version 0.8.0 and following the https://github.com/oorestisime/gatsby-source-instagram/issues/24#issuecomment-640183001
when I run on localhost I get:
"The gatsby-source-instagram plugin has generated no Gatsby nodes", and when I check in graphql its not there "allInstaNodes".

Any idea what might be?

package.json ---->  "gatsby-source-instagram": "^0.8.0"

gatsby.config --->
  {
      resolve: `gatsby-source-instagram`,
      options: {
        username: 'instagram_username',
        access_token: 'access_token',
        instagram_id: 'id',
      },
    }

Thank you for the help :)

**Comment by maxsteenbergen** [comment]
@ngerbauld Are you sure you're using the Instagram ID (all numbers) instead of the username? Confusing, I know, but it should be 
```json
{
  resolve: gatsby-source-instagram,
  options: {
      username: 1234567,
   }
}
```

with the instagram_id and access_token not needed, if I'm not mistaken

**Comment by oorestisime** [comment]
if you are using an access token then you don't need a username. its intentended to be as a fallback.
now if you don't have a valid access token that would happen indeed.
is this the first time using the plugin? or was it working and you just updated?

**Comment by ngerbauld** [comment]
I was using before on version 0.7.0 and it was working, but not anymore. On localhost was working great but when try to build in Netlify was giving errors (just like many people reported up in the conversation). 

So I updated to version 0.8.0 but couldn't get the query anymore. 

The access token that I got was only valid for 3 months, until August. But should work anyway, right?

**Comment by oorestisime** [comment]
Was it working with an access token before or public scraping. Several people reported that the way to get an access token might not be working so i am trying to understand if something broke there :) 

if you weren't using an access token on 0.7.0 then can you try again public scraping on 0.8.0 ? make sure to use the correct username id as explained https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-posts

**Comment by ngerbauld** [comment]
yeii, it worked with public scraping!
Thanksss @oorestisime !

**Comment by oorestisime** [comment]
I need to take some time to investigate the freaking mess of getting a valid access token. this is annoying. 
If anybody wants to research this i am happy to not do it myself :D :D

**Comment by KishokanthJeganathan** [comment]
Hey @oorestisime 

Thanks for all this work on the plugin :) I ran into the same issue where I got this messege- The gatsby-source-instagram plugin has generated no Gatsby nodes

I then added the user ID of the Insta page instead of the username and it worked. Issue is that it gave me 50 posts from Instagram and they are not in the order they were published in :/ do you have any fix for this?

**Comment by oorestisime** [comment]
Timestamp should be available for each post so you could sort them based on that.

**Comment by andregmoeller** [comment]
> Issue is that it gave me 50 posts from Instagram and they are not in the order they were published in :/ do you have any fix for this?

Hey @KishokanthJeganathan,
as already mentioned, you need to sort the returned list of elements. I expect that something like
```
allInstaNode(limit: 50, sort: { fields: timestamp, order: DESC }) {
…
}
```
should work.

**Comment by KishokanthJeganathan** [comment]
@oorestisime @andregmoeller worked like a charm! Thanks heaps :)

**Comment by Grsmto** [comment]
>Can anyone try getting a permanent token using this https://github.com/Bnjis/Facebook-permanent-token-generator ?

I tried and I don't think it works (anymore?).
Also the latest Facebook API version 7.0 doesn't let you create a permanent token, it's only 60 days maximum afaik. If anyone has more infos!

**Comment by PaulKleinschmidt** [comment]
Hey @oorestisime, I may be missing something here

I'm trying to use the public scraping for a user's profile. After updating the gatsby-source-instagram to version 0.8.0, and updating my config to look like this (using instagram id instead of username):

```
{
   resolve: `gatsby-source-instagram`,
   options: {
     type: `user-profile`,
     username: `my-instagram-id`
   }
},
``` 

I'm getting the following error on my netlify build 

```
4:49:05 PM: Could not fetch instagram user. Error status TypeError: Cannot destructure property `user` of 'undefined' or 'null'.
4:49:05 PM: error #11321 PLUGIN Cannot read property 'id' of null
4:49:05 PM: "gatsby-source-instagram" threw an error while running the sourceNodes lifecycle:
4:49:05 PM: Cannot read property 'id' of null
4:49:05 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
4:49:06 PM: 
4:49:06 PM: 
4:49:06 PM:   TypeError: Cannot read property 'id' of null
4:49:06 PM:   
4:49:06 PM:   - gatsby-node.js:76 createUserNode
4:49:06 PM:     [repo]/[gatsby-source-instagram]/gatsby-node.js:76:15
```

My query looks like this 

```
const data = useStaticQuery(
    graphql`
      query {
        instaUserNode {
          edge_followed_by {
            count
          }
        }
      }
    `
  );
```

Thank you for the help!!!

**Comment by oorestisime** [comment]
Folks please this is getting to be a huge thread and sometimes answers are just in the Readme.

https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-a-users-profile this no longer works as i mentioned.

If you want to get the posts of a profile then use this https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-posts

**Comment by joshua-isaac** [comment]
seems like https://codeofaninja.com/tools/find-instagram-user-id went down? give's an error when trying to spit out the id. working for anyone else?

**Comment by andregmoeller** [comment]
> seems like https://codeofaninja.com/tools/find-instagram-user-id went down? give's an error when trying to spit out the id. working for anyone else?

Please try the following steps:
1. Open a browser and enter the URL of the respective user's Instagram profile.
2. Add `?__a=1` to the URL – it should look similar to `https://www.instagram.com/username/?__a=1`
3. Take a look at `logging_page_id` element. It's value should start with `profilePage_`. The number that follows should be the respective user's instagram id.

**Comment by andregmoeller** [comment]
I agree with @joshua-isaac. https://codeofaninja.com/tools/find-instagram-user-id does not work any longer. Yesterday, I posted an alternative way to determine the Instagram id. Today, I noticed that you don't need to append `?__a=1`to the URL. You have just to open the respetive profile page in a browser, then open the source code (Firefox: CTRL+U / CMD+U, Chrome: CTRL+U / OPTION+CMD+U, Safari: OPTION+CMD+U) and search for `profilePage_`. The number that follows should be the Instagram ID.

It would be great if someone could confirm if it works or not. Thank you!

**Comment by oorestisime** [comment]
That's great @andregmoeller . Would you be able to open a PR to modify readme with this information?

**Comment by andregmoeller** [comment]
> That's great @andregmoeller . Would you be able to open a PR to modify readme with this information?

Sure, I am going to open a PR tomorrow.

**Comment by kuoloneous** [comment]
> I agree with @joshua-isaac. https://codeofaninja.com/tools/find-instagram-user-id does not work any longer. Yesterday, I posted an alternative way to determine the Instagram id. Today, I noticed that you don't need to append `?__a=1`to the URL. You have just to open the respetive profile page in a browser, then open the source code (Firefox: CTRL+U / CMD+U, Chrome: CTRL+U / OPTION+CMD+U, Safari: OPTION+CMD+U) and search for `profilePage_`. The number that follows should be the Instagram ID.
> 
> It would be great if someone could confirm if it works or not. Thank you!

Can confirm it works.  

Can we assume this method will no longer work after June 29th?

From https://www.instagram.com/developer/ :

> Q: Why should I migrate to the Instagram Graph API platform?
A: In January 2018, we publicly announced our plans to shut down the Instagram Legacy API platform through a sequenced approach. We plan to disable the final permission remaining on the Legacy API ("Basic Permission") on June 29, 2020 and any existing apps using the Legacy API will no longer have access. We encourage you to apply for permissions to Instagram Basic Display API and migrate Legacy API calls before June 29 to avoid interruption of service to your app and business. Note that App Review submissions can take up to a week or longer to process. Refer to the developer documentation to learn more.

>Q: Can I continue using the Instagram Legacy API platform after June 29?
A: No, the Legacy API platform will no longer be available as of June 29. We encourage you to apply for permissions to the Instagram Basic Display API via App Review.

**Comment by oorestisime** [comment]
Well i hope it will work through the summer since i will be a lot of time away and won't be able to fix. I thought it will work until end of september.
My plan is to eventually find a nice easy way to generate graph api tokens so that everybody can use this method until the dust settles with all their API changes and find a convenient way to do public scraping.

**Comment by balibebas** [comment]
As a reprieve for anyone needing to create an ad hoc Fakebook account to get access to IG stuffs may I introduce you to one of my favorite new cloud services: real SIM-less telephone numbers and SMS which work for Google/Facebook/Twitter/OkCupid:

https://crypton.sh
http://cryptonthxdxebhb.onion/

Use it to create a Facebook account, Instagram whatever. Numbers are not recycled like those Ft aree apps and no ads.

Further Reading: https://habd.as/post/living-without-sim-card/

**Comment by balibebas** [comment]
As a reprieve for anyone needing to create an ad hoc Fakebook account to get access to IG stuffs may I introduce you to one of my favorite new cloud services: real SIM-less telephone numbers and SMS which work for Google/Facebook/Twitter/OkCupid:

https://crypton.sh
http://cryptonthxdxebhb.onion/

Use it to create a Facebook account, Instagram whatever. Numbers are not recycled like the free apps and there are no ads.

Further Reading: https://habd.as/post/living-without-sim-card/

**Comment by meeroslav** [comment]
> I agree with @joshua-isaac. https://codeofaninja.com/tools/find-instagram-user-id does not work any longer. Yesterday, I posted an alternative way to determine the Instagram id. Today, I noticed that you don't need to append `?__a=1`to the URL. You have just to open the respetive profile page in a browser, then open the source code (Firefox: CTRL+U / CMD+U, Chrome: CTRL+U / OPTION+CMD+U, Safari: OPTION+CMD+U) and search for `profilePage_`. The number that follows should be the Instagram ID.
> 
> It would be great if someone could confirm if it works or not. Thank you!

Perhaps even simpler would be to check your cookie for Instagram page and look for key `ds_user_id` (should be the last item in the cookie).

**Comment by Aarekaz** [comment]
![image](https://user-images.githubusercontent.com/36888347/87138089-a4571780-c2bd-11ea-9cb8-62aa1c8bc956.png)
I followed a lot of guides and even did [this](https://developers.facebook.com/docs/instagram-basic-display-api/getting-started)
and used the end id but I still get the same error. I just want to show my posts in my website nothing more. 
I spent my whole day looking into this, but still cant figure it out. My version is 0.8.0

**Comment by balibebas** [comment]
@Aarekaz It works using the Graph API. I just creted an IG/Facebook account a few days ago and, while it wasn't exactly smooth sailing, persistence paid off in the end. Make sure you follow the instructions carefully. Make sure your using an instagram business acount. Make sure you have a Facebook page linked to your Instagram Business account. And make sure you're not trying to use the temporary token (even though it might look the same at the beginning).

**Comment by ghost** [comment]
@Aarekaz It works using the Graph API. I just created an IG/Facebook account a few days ago and, while it wasn't exactly smooth sailing, persistence paid off in the end. Make sure you follow the instructions carefully. Make sure your using an instagram business acount. Make sure you have a Facebook page linked to your Instagram Business account. And make sure you're not trying to use the temporary token (even though it might look the same at the beginning as the long-lease token).

**Comment by Aarekaz** [comment]
@balibebas  Looks like its working. I just used the inspect element ID, But I doubt that is a temp solution!

Hope a permanent solution comes along with all this API changes.

**Comment by wouter-dev** [comment]
> Folks please this is getting to be a huge thread and sometimes answers are just in the Readme.
> 
> https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-a-users-profile this no longer works as i mentioned.
> 
> If you want to get the posts of a profile then use this https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-posts

I tried this (the Instagram ID method) and it works locally but fails to deploy to Netlify. I don't have a Facebook account. Any idea?

**Comment by jedifunk** [comment]
unable to get the Graph API working, `allInstaNode` doesn't even show up in graphiql ... any thoughts?

**Comment by peiche** [comment]
I can't seem to get `carouselImages` working. Does someone have an example of this functioning?

**Comment by samason** [comment]
This issue has resurfaced for me just recently; public scraping works locally but is failing with the same error as earlier last year on Netlify builds. Seems like there's been an update on the Instagram side?

**Comment by listiani13** [comment]
@samason ran into the same issue yesterday, seems to be working if you use the [Graph API ](https://github.com/oorestisime/gatsby-source-instagram#graph-api)

**Comment by brianshimkus** [comment]
This issue also just resurfaced for me. I tried gatsby clean, uninstalling the packages and reinstalling, different versions, etc. without being able to get a successful build with Netlify.

**Comment by alexanderdejong** [comment]
Yeah it's happing to me too. I think perhaps it could be caused when you have too many builds and instagram gives the login wall. I will try again later and see if the problem persists.

**Comment by brianshimkus** [comment]
I tried another build today after doing nothing with the code since the comment above and now it builds just fine with Netlify. Weird.

**Comment by samason** [comment]
I ended up making an AJAX request to the same endpoint the plugin uses right within my React component, although you lose some of the benefits of this plugin that seems to be more reliable and has the added benefit of not requiring a site build to get updated posts from Instagram (and although it sounds like the legit, non public scraping method works, as people have mentioned above it's pretty tedious to set up).

**Comment by ajdorexyz** [comment]
> 
> 
> I ended up making an AJAX request to the same endpoint the plugin uses right within my React component, although you lose some of the benefits of this plugin that seems to be more reliable and has the added benefit of not requiring a site build to get updated posts from Instagram (and although it sounds like the legit, non public scraping method works, as people have mentioned above it's pretty tedious to set up).

I was up until recently, calling a netlify lambda function and passing the required Instagram ID as a parameter to fetch data from the same endpoint this plugin uses. - (In a manner similar to what Wes Bos does in this video https://www.youtube.com/watch?v=9Ryc5MQTUYc). 

recently in production I started getting 502 errors, and bad requests when running the functions on netlify. like @samason, I moved the logic from the serverless function directly into the react component, whereby I'm calling an async function inside the useEffect hook.

For the time being i'm not having any issues with this method, and for the particular usecase I have - been getting the aforementioned benefits of not having to trigger a rebuild to collect new instagram data, alongside live updates that you can cache within your component if neccessary, is pretty good.

**Comment by oorestisime** [comment]
Sorry for late reply. Seesm another login wall by instagram. 
Unfortunately i dont have time right now to see what i could do to bypass.

I think its clear instagram doesnt want us to public scraping :) i suggest to move to Graph API as soon as possible but there's nothing much i can do to save the public scraping

**Comment by dbertella** [comment]
@samason can you share some code example on what you've done? Can you fetch instagram as not authenticated user?
Ok I see this right? 
```
https://instagram.com/graphql/query/?query_id=17888483320059182&variables={"id":"${username}","first":100,"after":null}
```
I think I'll have a go, today my buids start to fail again even if I was using the id method

**Comment by dbertella** [comment]
Ok just in case someone want to follow this path this is my attempt to fetch all the instagram phost from the client
```
// https://github.com/oorestisime/gatsby-source-instagram/blob/master/src/instagram.js
const igUrl = (userId) =>
  `https://instagram.com/graphql/query/?query_id=17888483320059182&variables={"id":"${userId}","first":12,"after":null}`;

...

  const [allInsta, setAllInsta] = useState([]);
  useEffect(() => {
    fetch(igUrl(IG_ID))
      .then((j) => j.json())
      .then(({ data }) => {
        const photos = [];
        data.user.edge_owner_to_timeline_media.edges.forEach((edge) => {
          if (edge.node) {
            photos.push({
              id: edge.node.id,
              thumbnail: edge.node.thumbnail_resources[2].src, // here I'm getting some data I need to display later, but more are contained in the response
              caption: edge.node.edge_media_to_caption.edges[0].node.text,
            });
          }
        });
        setAllInsta(photos);
      });
  }, []);
  ```

**Comment by LarsBehrenberg** [comment]
I encountered this issue as well last year. And I don't think it's this plugin's fault, but rather down to Instagram doing weird stuff.  In the meantime, I also went with fetching the posts manually and wrote a blog post about how to do so.
Here are some links to explanation in the [blog post](https://blog.larsbehrenberg.com/use-javascripts-fetch-api-with-asyncawait-to-fetch-your-instagram-feed-in-react), [code](https://github.com/LarsBehrenberg/gatsby-instagram-feed/blob/master/src/components/instagram.js), and [working demo](https://gatsby-instagram-feed.netlify.app/).

**Comment by owenhoskins** [comment]
> Here are somelinks to explanation in the [blog post](https://blog.larsbehrenberg.com/use-javascripts-fetch-api-with-asyncawait-to-fetch-your-instagram-feed-in-react), [code](https://github.com/LarsBehrenberg/gatsby-instagram-feed/blob/master/src/components/instagram.js), and [working demo](https://gatsby-instagram-feed.netlify.app/).

Hey @LarsBehrenberg, thanks for sharing! The method you describe is using the same end-point as the current [Public scraping for posts](https://github.com/oorestisime/gatsby-source-instagram#public-scraping-for-posts): 

`https://www.instagram.com/graphql/query?query_id=17888483320059182&variables={"id":"${INSTAGRAM_ID}","first":${PHOTO_COUNT},"after":null}` 

I see that it is working in the demo. But I wonder if it would also suffer from the same "rate-limiting" login wall that the we've been hitting lately. 

In my use-case, for an artist's representation agency, I am scrapping the posts of 60+ Instagram accounts and after a few builds within a short time-frame we face the login wall. I wonder if the dynamic component would suffer a similar fate if the page had many visitors and thus many requests to end-point?

**Comment by LarsBehrenberg** [comment]
@owenhoskins Good question! That might as well be the case. I haven't run into any issues using this method yet and been using it for the last 8 months or so. So I guess you'll just have to try out and see what happens... Sorry for not being more helpful :S

**Comment by radscheit** [comment]
@LarsBehrenberg Thanks for your effort and I like the approach. But currently, your demo isn't working any longer – at least for me:

![Screenshot 2021-02-16 at 08 47 20](https://user-images.githubusercontent.com/6578648/108033159-df7baf00-7033-11eb-80f8-6fc5dca28287.png)

**Comment by LarsBehrenberg** [comment]
> @LarsBehrenberg Thanks for your effort and I like the approach. But currently, your demo isn't working any longer – at least for me:
> 
> 
> 
> ![Screenshot 2021-02-16 at 08 47 20](https://user-images.githubusercontent.com/6578648/108033159-df7baf00-7033-11eb-80f8-6fc5dca28287.png)
> 
> 

Note sure, just checked and it's working fine for me.

**Comment by radscheit** [comment]
> > @LarsBehrenberg Thanks for your effort and I like the approach. But currently, your demo isn't working any longer – at least for me:
> > ![Screenshot 2021-02-16 at 08 47 20](https://user-images.githubusercontent.com/6578648/108033159-df7baf00-7033-11eb-80f8-6fc5dca28287.png)
> 
> Note sure, just checked and it's working fine for me.

I can reproduce these errors by using the same IP address, but it works by changing my IP address via VPN. So is the consumption of that API depending on the end-users rate limit?

**Comment by Piligrimas** [comment]
> > @LarsBehrenberg Thanks for your effort and I like the approach. But currently, your demo isn't working any longer – at least for me:
> > ![Screenshot 2021-02-16 at 08 47 20](https://user-images.githubusercontent.com/6578648/108033159-df7baf00-7033-11eb-80f8-6fc5dca28287.png)
> 
> Note sure, just checked and it's working fine for me.

Hi, I used your method, but it is not working anymore? It says that CORS policy blocking it. Is it in my or Instagram side?
![image](https://user-images.githubusercontent.com/76046524/109081724-d2a73b80-7756-11eb-8f28-b67debc6113f.png)

**Comment by VT-Web-Development** [comment]
> ![image](https://user-images.githubusercontent.com/36888347/87138089-a4571780-c2bd-11ea-9cb8-62aa1c8bc956.png)
> I followed a lot of guides and even did [this](https://developers.facebook.com/docs/instagram-basic-display-api/getting-started)
> and used the end id but I still get the same error. I just want to show my posts in my website nothing more.
> I spent my whole day looking into this, but still cant figure it out. My version is 0.8.0

That exactly what happened when I deployed to Netlify.

**Comment by tijsluitse** [comment]
Same here @VT-Web-Development! were you able to fix it? Having this issue on multiple websites now..

**Comment by VT-Web-Development** [comment]
> Same here @VT-Web-Development! were you able to fix it? Having this issue on multiple websites now..

No - I am not using it for now. I will try another solutions.

**Comment by joshua-isaac** [comment]
Has anyone found a solution to this or a solution in general on how to get Instagram data in a react/gatsby app?

**Comment by beamercola** [comment]
@joshua-isaac The only thing that works for me is Zapier > Airtable

**Comment by VT-Web-Development** [comment]
> @joshua-isaac The only thing that works for me is Zapier > Airtable

But you have to pay for it.

**Comment by Aarekaz** [comment]
Any updates? I have been having this issue and its preventing deploying.
![image](https://user-images.githubusercontent.com/36888347/112656027-13d75c00-8e79-11eb-82d6-2846cbd3c20f.png)

**Comment by oorestisime** [comment]
Hi, just to give a heads up.

There is nothing to do here for the plugin. Its on instagram to stop their paywalls i cant do anything :(
The reason i am keeping this ticket open is because it has a lot of information for anyone who wishes to read.

**Comment by SignetOHara** [comment]
Hi everyone, thanks for this thread. 

So just to clarify, if we use the Graph API method rather than public scraping are there still issues? If not, does anyone know of any up to date tutorial/guides on how to set up? Instagram/FB seem to want to make it as convoluted as possible...

I'm using public scraping during development and it usually works as long as the dev server isn't restarted numerous times (which fits with what everyone is saying). Haven't yet deployed to Netlify though.

**Comment by mcljs** [comment]
![image](https://user-images.githubusercontent.com/52798639/114501523-2632f300-9bf8-11eb-830c-e3bdc4585cfb.png)
Hello everyone today, in the morning I installed the gatsby-source-instagram plugin and it helped me, when I go to make other changes right now at night it no longer grabs me, I get this and it has not succeeded in grabbing my nodes. Somebody could help me?

**Comment by tijsluitse** [comment]
Hey there, I found out that my access token was no longer valid. After creating a new version via the steps explained here: [https://www.gatsbyjs.com/plugins/gatsby-source-instagram/#instagram-graph-api-token](https://www.gatsbyjs.com/plugins/gatsby-source-instagram/#instagram-graph-api-token), the public scraping worked again. You can check out your token here: [https://developers.facebook.com/tools/debug/accesstoken/](https://developers.facebook.com/tools/debug/accesstoken/).

**Comment by matteocarpi** [comment]
hey @tijsluitse thanks for the links! 

I was facing this issue and I followed that procedure and was able to get an access token. Though unfortunately I wasn't able to get a token that never expires :/. Simply when I click "debug" for the second time I get told it still expires in three months.

The only thing that I had to do different is using v10.0 of the Graph API, as I had no other option given in the Explorer.

**Comment by kanlanc** [comment]
@matteocarpi I have the same thing that I cannot access any other API version, but I cant find the permissions mentioned, were they available for you?

**Comment by matteocarpi** [comment]
hey @kanlanc yes, but it was tricky. 

When you click on "Generate Access Token" and a new window pops up, you should be able to click on "Edit settings" or something similar, and allow the app to access the facebook page connected to the instagram account (if that makes sense). at that point, once you confirm and go back to the API Explorer, you should be able to see all the permissions you need.

Hope that helps :)

**Comment by knhn1004** [comment]
same, my clients bothered me recently and I still cannot resolve the issue
I would have to remove the "Posts" area for their website temporarily
seems like an issue with the connection between netlify and instagram

**Comment by radscheit** [comment]
> same, my clients bothered me recently and I still cannot resolve the issue
> I would have to remove the "Posts" area for their website temporarily
> seems like an issue with the connection between netlify and instagram

It looks to me like if there is a volume cap on IP addresses, here for netlify's build servers. That's why it's volatile.

**Comment by kekshibata** [comment]
So, public scraping is no longer available...?
It works for me on local development, but on gatsby cloud build it fails

**Comment by reaganchisholm** [comment]
> So, public scraping is no longer available...?
> It works for me on local development, but on gatsby cloud build it fails

Public scraping will fail more frequently on hosting sites like Netlify and Gatsby Cloud because there are likely many sites doing public scraping on Instagram via those hosts. Instagram then rate limits those host servers by returning a login page, which causes most builds using public scraping to fail on those hosts.

**Comment by oorestisime** [comment]
Closing this as i dont think we can do anything more here!
